//General
export const SET_LANGUAGE = 'SET_LANGUAGE';
export const SET_TRANSLATIONS = 'SET_TRANSLATIONS';
export const SET_GLOBAL_LOADING = 'SET_GLOBAL_LOADING';
export const SET_COUNTRIES = 'SET_COUNTRIES';
export const SET_PAGE_TITLE = 'SET_PAGE_TITLE';


//messages
export const MESSAGE_REMOVE = 'MESSAGE_REMOVE';
export const MESSAGE_REMOVE_BY_KEY = 'MESSAGE_REMOVE_BY_KEY';
export const MESSAGE_ADD = 'MESSAGE_ADD';


//Home
export const BANNERS_LIST_GET_REQUEST = 'BANNERS_LIST_GET_REQUEST';
export const BANNERS_LIST_GET_SUCCESS = 'BANNERS_LIST_GET_SUCCESS';
export const BANNERS_LIST_GET_FAILURE = 'BANNERS_LIST_GET_FAILURE';

export const CATEGORIES_PREVIEW_LIST_GET_REQUEST = 'CATEGORIES_PREVIEW_LIST_GET_REQUEST';
export const CATEGORIES_PREVIEW_LIST_GET_SUCCESS = 'CATEGORIES_PREVIEW_LIST_GET_SUCCESS';
export const CATEGORIES_PREVIEW_LIST_GET_FAILURE = 'CATEGORIES_PREVIEW_LIST_GET_FAILURE';

export const HOME_STORE_RESET = 'HOME_STORE_RESET';

//Sculpture
export const SCULPTURES_LIST_GET_REQUEST = 'SCULPTURES_LIST_GET_REQUEST';
export const SCULPTURES_LIST_GET_SUCCESS = 'SCULPTURES_LIST_GET_SUCCESS';
export const SCULPTURES_LIST_GET_FAILURE = 'SCULPTURES_LIST_GET_FAILURE';

export const SCULPTURES_STORE_RESET = 'SCULPTURES_STORE_RESET';

//Exterior/Interior
export const EXTERIOR_INTERIOR_LIST_GET_REQUEST = 'EXTERIOR_INTERIOR_LIST_GET_REQUEST';
export const EXTERIOR_INTERIOR_LIST_GET_SUCCESS = 'EXTERIOR_INTERIOR_LIST_GET_SUCCESS';
export const EXTERIOR_INTERIOR_LIST_GET_FAILURE = 'EXTERIOR_INTERIOR_LIST_GET_FAILURE';

export const EXTERIOR_INTERIOR_STORE_RESET = 'EXTERIOR_INTERIOR_STORE_RESET';

//Painting
export const PAINTING_LIST_GET_REQUEST = 'PAINTING_LIST_GET_REQUEST';
export const PAINTING_LIST_GET_SUCCESS = 'PAINTING_LIST_GET_SUCCESS';
export const PAINTING_LIST_GET_FAILURE = 'PAINTING_LIST_GET_FAILURE';

export const PAINTING_STORE_RESET = 'PAINTING_STORE_RESET';


//Publication
export const PUBLICATION_LIST_GET_REQUEST = 'PUBLICATION_LIST_GET_REQUEST';
export const PUBLICATION_LIST_GET_SUCCESS = 'PUBLICATION_LIST_GET_SUCCESS';
export const PUBLICATION_LIST_GET_FAILURE = 'PUBLICATION_LIST_GET_FAILURE';

export const PUBLICATION_STORE_RESET = 'PUBLICATION_STORE_RESET';
